basePath: /v1
host: 0.0.0.0
info:
  contact:
    name: mirpo
    url: https://github.com/mirpo
  description: This is a REST API for storing logs in immudb from different services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - health
swagger: "2.0"
